version: '2'
services:
  logstash:
    build: logstash
    ports:
      - "5000:5000"
    links:
      - elasticsearch:es
  elasticsearch:
    build: elasticsearch
    ports:
      - "9200:9200"
  kibana:
    build: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch:es
